### ISSUE TITLE
Duplicate files error while running was as react-native backend after reloading.

### ISSUE THREAD

**Issue by Sulochan-khadka** [react/metro#1122]
The aim of the solution is to be able to run aws as react-native backend smoothly.

Current status:
DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:450:17)
    at workerReply (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:507:9)

mockPath1: 'amplify/backend/function/rideshare06b2bc5606b2bc56PostConfirmation/src/package.json',
  mockPath2: 'amplify/#current-cloud-backend/function/rideshare06b2bc5606b2bc56PostConfirmation/src/package.json'
}
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:450:17)
    at workerReply (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:507:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 19)
    at async HasteMap._applyFileDelta (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:672:7)
    at async /Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro-file-map/src/index.js:327:9
    at async DependencyGraph.ready (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)
    at async Bundler.ready (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro/src/Bundler.js:69:5)
    at async IncrementalBundler.ready (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro/src/IncrementalBundler.js:289:5)
    at async Server.ready (/Users/sulochankhadka/Desktop/RideShare/RideShare/node_modules/metro/src/Server.js:1085:5)

**Comment by ingridswiftconnect** [comment]
I have the same issue ... Do we have a solution for this?

**Comment by robhogan** [comment]
Apologies this didn't get a reply.

Same as #1109 - Amplify's `#current-cloud-backend` mirrors each function's `package.json`, and with global package resolution enabled every `package.json` outside `node_modules` is indexed by its `name`. The two are ambiguous, so disallowed.

That became opt-in via `resolver.enableGlobalPackages` in Metro 0.79 and is off by default, so a current project won't hit it unless it sets that. If you do want it on, exclude the mirror with `resolver.blockList`.

Closing as a duplicate of #1109.
