### ISSUE TITLE
Unable to resolve module stream

### ISSUE THREAD

**Issue by shkdev94** [react/metro#1196]
lm developiing in pnpm workspace. when I use the unstable_enablePackageExports option, I get the following error.  whats wrong?

```
error: Error: Unable to resolve module stream from /Users/sanghyeon/projects/plzsub/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/stream.js: stream could not be found within the project or in these directories:
  ../../../node_modules/.pnpm/ws@8.16.0/node_modules
  ../../../node_modules
  1 | 'use strict';
  2 |
> 3 | const { Duplex } = require('stream');
    |                             ^
  4 |
  5 | /**
  6 |  * Emits the `'close'` event on a stream.
    at ModuleResolver.resolveDependency (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:153:15)
    at DependencyGraph.resolveDependency (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/node-haste/DependencyGraph.js:279:43)
    at /Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/lib/transformHelpers.js:176:21
    at resolveDependencies (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:56:25)
    at visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:107:30)
    at async Promise.all (index 1)
    at async visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
    at async Promise.all (index 8)
    at async visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
    at async Promise.all (index 0)
```

this is my metro config
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const path = require('path');

const watchFolders = [
  path.resolve(path.join(__dirname, '../../../node_modules')),
  path.resolve(path.join(__dirname, '../../../packages')),
];

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  resolver: {
    unstable_enablePackageExports: true,
  },
  watchFolders,
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

this is my dev env
```
os: mac ventura 13.6.3
reac-native: 0.73.2
pnpm: 8.13.1
node: 20.10.0
```

thank you :)

**Comment by robhogan** [comment]
Hi @boh001. `ws` is a WebSocket implementation for Node.js, and not compatible (or necessary) for the browser or React Native (which has a native [`WebSocket` global](https://reactnative.dev/docs/network#websocket-support).

If you're not importing `ws` directly it might be a dependency of one of your dependencies. 

If you have a require stack, we can see why it's being imported. It may be that an intermediate dependency is resolving to a Node.js version.

**Comment by boh001** [comment]
@robhogan thank you for reply. I think that's all there is to the require stack

error: Error: Unable to resolve module stream from /Users/sanghyeon/projects/plzsub/node_modules/.pnpm/ws@8.16.0/node_modules/ws/lib/stream.js: stream could not be found within the project or in these directories:
  ../../../node_modules/.pnpm/ws@8.16.0/node_modules
  ../../../node_modules
  1 | 'use strict';
  2 |
> 3 | const { Duplex } = require('stream');
    |                             ^
  4 |
  5 | /**
  6 |  * Emits the `'close'` event on a stream.
    at ModuleResolver.resolveDependency (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:153:15)
    at DependencyGraph.resolveDependency (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/node-haste/DependencyGraph.js:279:43)
    at /Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/lib/transformHelpers.js:176:21
    at resolveDependencies (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:56:25)
    at visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:107:30)
    at async Promise.all (index 1)
    at async visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
    at async Promise.all (index 8)
    at async visit (/Users/sanghyeon/projects/plzsub/node_modules/.pnpm/metro@0.80.3/node_modules/metro/src/DeltaBundler/buildSubgraph.js:116:5)
    at async Promise.all (index 0)

but i dont understand why it doesn't work when unstable_enablePackageExports is enabled. i guess if problem is ws as you said, It should have been equally bad when this option is disabled, but it works.

**Comment by robhogan** [comment]
> but i dont understand why it doesn't work when unstable_enablePackageExports is enabled. i guess if problem is ws as you said, It should have been equally bad when this option is disabled, but it works.

It's probably upstream of `ws` - my guess is that you have a dependency which only requires `ws` when running under Node.js, and it's the entry point to that dependency that's being resolved differently with `unstable_enablePackageExports`. You'd need to find out what's requiring `ws` - `pnpm why ws` might have some clues.

**Comment by boh001** [comment]
`pnpm why ws` shows nothing. it's so weird. for now, it looks like the only way is to disable this option. is it okay to leave the issue open for people have the same problem? Maybe someone will solve it one day :)

**Comment by robhogan** [comment]
Closing as we never identified the dependency chain.

For anyone arriving here: without `exports`, Metro picks an entry point via `resolverMainFields` (`react-native`, `browser`, `main`), so a package shipping a browser build gets that. With package exports enabled, a match in `exports` takes precedence and those fields aren't consulted - so a package whose `exports` map has no `browser` or `react-native` condition may point to a node-targeting version, which requires Node core modules like `stream`.

The fix is to find that dependency and get it resolving to its browser or React Native entry. `resolver.resolveRequest` is the escape hatch if it can't be fixed upstream.
