### ISSUE TITLE
Unable to resolve module missing-asset-registry-path

### ISSUE THREAD

**Issue by A-Kasaaian** [react/metro#1368]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I see following error when I build production bundle
```
Error: Unable to resolve module missing-asset-registry-path from /Users/XXX/Develop/XXX/node_modules/@react-navigation/elements/lib/commonjs/assets/back-icon-mask.png: missing-asset-registry-path could not be found within the project or in these directories:
  node_modules/@react-navigation/elements/node_modules
  node_modules
> 1 | �PNG
  2 | 
  3 | 
  4 | IHDR2���gAMA��
                    �a cHRMz&�����u0�`:�p��Q<bKGD���̿tIME�
  2 | 
  3 | 
  4 | IHDR2���gAMA��
                    �a cHRMz&�����u0�`:�p��Q<bKGD���̿tIME�.
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
on react native project
`cd android && ./gradlew bundleRelease`

**What is the expected behavior?**
Metro should process images

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

const config = {
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config)

I have already tried most of configs shared on this repo and react-native repo or stackoverflow.

**Comment by robhogan** [comment]
Hi @A-Kasaaian, you don't mention what versions of RN/Metro/(Expo?) you're using, which might be helpful, but that looks like your configuration isn't being picked up at all - ie the CLI isn't finding your config file. 

What's your project structure and what's the name and location of your config file?

**Comment by A-Kasaaian** [comment]
All was working on RN 70.6 but I had to upgrade packages. I ended up with  current latest versions of metro and RN (75.4).

I had the same error for my project images but I resolved them by changing Image attribute `resource ={require('@assets/image.png')}` to `source={{ uri: '@assets/image.png'}}`.

**Comment by robhogan** [comment]
I'm not sure whether you're saying this can be closed? 

If not could you describe your project structure and Metro config path?

**Comment by gkasireddy202** [comment]
I am facing the same issue in RN@0.78.0
Here is the metro config file.

const { getDefaultConfig } = require('expo/metro-config');
const { mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('@react-native/metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);

**Comment by cvincentcoleman** [comment]
Same issue here. It's been a major blocker for us upgrading from 0.73.5 -> 0.77.1

**Comment by A-Kasaaian** [comment]
Can you send your config?

**Comment by yolandaccc** [comment]
am facing the same issue in RN@0.75.5

uograde from 0.64.8 to 0.75.5 ,ios, M1,use simulator

![Image](https://github.com/user-attachments/assets/34a09850-1d53-48e7-80cb-ccbef652fe26) It is ok on0.64.8.I can't upload IOS APP,so I update Xcode(15.3->16) ,React-native, my computer IOS system.I met this issue. I ask ChatGPT .I changed defualt metro.config.js to this,it dose not work. I  tried to change the picture, build again,it seems work. but the issue come to another picture.why?I can't run😭
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
    resolver: {
      assetExts: [...assetExts, 'png', 'jpg', 'jpeg', 'bmp', 'gif', 'webp'],
      sourceExts: [...sourceExts, 'jsx', 'js', 'ts', 'tsx'],
    },
  };
})();

**Comment by ltujiba** [comment]
+1 happened on RN 80.2

**Comment by danfq** [comment]
Same here, React Native `0.78.3` - last one to support `react-native-macos`.

**Comment by efstathiosntonas** [comment]
happened on rn@0.81.4, `node --max_old_space_size=16000 node_modules/react-native/cli.js start --reset-cache --client-logs` and: 

```json
    "metro": "0.83.2",
    "metro-cache": "0.83.2",
    "metro-config": "0.83.2",
    "metro-core": "0.83.2",
    "metro-resolver": "0.83.2",
    "metro-runtime": "0.83.2",
    "metro-source-map": "0.83.2",
```

```log
Error: Unable to resolve module missing-asset-registry-path from /Users/stathis/IdeaProjects/xxxxx/src/assets/common/landing_background.png: missing-asset-registry-path could not be found within the project or in these directories:
  node_modules
> 1 | �PNG
  2 |
  3 |
  4 | IHDR�o��,~PLTE�.w�c`�\^�__�a_�ga�[^�Y]�fasԼ�ia�Z^�W]�6u�]e�Co�Ng�Jl�2v�Yg�Tj�Tb�:s�Lm�˸�>r�Gk�J��=|�=o������̀��`�������Ċ��u��´�U��I��k�Ψ{��IDATx�̜���0
                          E����@H�@���Il��/����&N��b_�ɼ��y��G�骶;#M61�նm�諾˿��_{km�V��!Qgy,?nud8!�����s��
    at ModuleResolver.resolveDependency (/Users/stathis/IdeaProjects/xxxxxx/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:172:15)
    at DependencyGraph.resolveDependency (/Users/stathis/IdeaProjects/xxxxxx/node_modules/metro/src/node-haste/DependencyGraph.js:252:43)
    at /Users/stathis/IdeaProjects/xxxx/node_modules/metro/src/lib/transformHelpers.js:163:21
    at resolveDependencies (/Users/stathis/IdeaProjects/xxxx/node_modules/metro/src/DeltaBundler/buildSubgraph.js:43:25)
    at visit (/Users/stathis/IdeaProjects/xxxxx/node_modules/metro/src/DeltaBundler/buildSubgraph.js:81:30)
    at async Promise.all (index 7)
    at async visit (/Users/stathis/IdeaProjects/xxxxx/node_modules/metro/src/DeltaBundler/buildSubgraph.js:90:5)
    at async Promise.all (index 23)
    at async visit (/Users/stathis/IdeaProjects/xxxx/node_modules/metro/src/DeltaBundler/buildSubgraph.js:90:5)
    at async Promise.all (index 0)
```

`yarn add -D missing-asset-registry-path`  won't solve it since it does not export proper package from main. 

<details>

<summary>click for metro config</summary>

```js
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const { withSentryConfig } = require('@sentry/react-native/metro');

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig(__dirname);
  const { assetExts, sourceExts } = defaultConfig.resolver;

  const isProduction = process.env.NODE_ENV === 'production';

  const getTransformOptions = async () => ({
    transform: {
      experimentalImportSupport: true,
      inlineRequires: true,
      nonInlinedRequires: [
        'React',
        'react',
        'react-compiler-runtime',
        'react/jsx-dev-runtime',
        'react/jsx-runtime',
        'react-native'
      ]
    }
  });

  const metroConfig = {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer/react-native'),
      getTransformOptions,
      hermesParser: true,
      optimizationSizeLimit: 200 * 1024,
      unstable_compactOutput: isProduction,
      unstable_disableModuleWrapping: false,
      unstable_disableNormalizePseudoGlobals: true
    },
    resolver: {
      assetExts: [...assetExts.filter((ext) => ext !== 'svg'), 'bin', 'lottie'],
      sourceExts: [...sourceExts, 'svg'],
      enableGlobalPackages: true,
      unstable_enablePackageExports: false,
      resolverMainFields: ['react-native', 'browser', 'main'],
      useWatchman: true,
      disableHierarchicalLookup: false
    },
    watcher: {
      unstable_lazySha1: true,
      unstable_workerThreads: true,
      unstable_autoSaveCache: {
        enabled: true,
        debounceMs: 3000
      },
      watchman: {
        deferStates: ['hg.update']
      }
    },
    server: {
      port: 8081
    },
    maxWorkers: process.env.MAX_WORKERS
      ? parseInt(process.env.MAX_WORKERS, 10)
      : Math.max(2, Math.floor(require('os').cpus().length * 0.75)),
    resetCache: true,
    cacheVersion: '1.0',
    stickyWorkers: true
  };

  const config = mergeConfig(defaultConfig, metroConfig);
  return withSentryConfig(config, {
    annotateReactComponents: true
  });
})();
```

</details>

**Comment by efstathiosntonas** [comment]
this is fixed on 0.83.3 (at least on rn@0.81.4) 

cc: @robhogan just fyi

**Comment by jiroscripts** [comment]
I'm encountering the same problem in a monorepo with dependencies installed in the root directory. Has anyone found a solution?

**Comment by robhogan** [comment]
`assetRegistryPath` defaults to the literal string `missing-asset-registry-path` in `metro-config`, so this error always means Metro is running without React Native's config applied, [as above](https://github.com/react/metro/issues/1368#issuecomment-2404556350).

A few different causes are mixed into this thread. Metro 0.83.0 to 0.83.2 had two config-loading regressions, promise-returning config files (#1586) and `mergeConfig` given a partial first argument, both fixed in 0.83.3 - that matches @efstathiosntonas's report. Errors thrown while evaluating `metro.config.js` were also being obscured until [af3bccab](https://github.com/react/metro/commit/af3bccabf0c6), in the same release.

The `@react-native/assets-registry/registry` variant is a different failure. There the config was applied, and it's that package which can't be resolved from the asset's directory, which points at hoisting rather than config. Please open a new issue if you're seeing that.
