### ISSUE TITLE
Couldn't find preset "module:metro-react-native-babel-preset" when running jest

### ISSUE THREAD

**Issue by michaelknoch** [react/metro#242]
**Do you want to request a *feature* or report a *bug*?** 
bugreport

**What is the current behavior?**
I updated a react-native codebase from 0.56 to 0.57 and migrated from `"babel-preset-react-native": "^2.1.0"` to  the current version of `"metro-react-native-babel-preset"`. The app itself compiles and runs for iOS and android but all of the jest tests crash immediately on my mac and on our linux ci.

```
Test suite failed to run
Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/Users/michaelknoch/dev/repos/JestCrashReproduction"
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
- clone https://github.com/michaelknoch/jest-metro-reproduction
- npm i
- npm run test

I created this repo with react-native init. To run Jest we need at leat one file with pattern `*.test.js`
So i ended up running this: `react-native init JestMetroCrash --version 0.57.0  && cd JestMetroCrash && touch App.test.js`

Its worth to mention that the test suite also breaks when .babelrc with explicit `"presets": ["module:metro-react-native-babel-preset"]` is provided. 

**What is the expected behavior?**
Jest should resolve the preset and transpile files correctly.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
node v8.11.3
npm 6.4.1
metro latest release

**Comment by ajcrites** [comment]
For your jest configuration, can you also add `transform: { '^.+\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js' }`?

**Comment by rafeca** [comment]
@mjesun do you know why `jest` is not able to pick up the preset?

**Comment by fmaso04** [comment]
I have found the same problem today. 
Open the file `.babelrc`, you will find it in the root of the project, and replace:

`{
  "presets": ["module:metro-react-native-babel-preset"]
}
`

to

`{
  "presets": ["react-native"]
}
`

**Comment by rajapanidepu** [comment]
Replacing with `{ "presets": ["react-native"] }` can't be the solution for the existing set of tests, as it breaks loading babel-jest and failing mocking files under tests that are imported using ES6.

**Comment by michaelknoch** [comment]
the solution from @ajcrites seems to work, but now everything mocked with jest.mock seem to break for some reasons. Is there any known breaking change about that?

**Comment by hkung77** [comment]
@ajcrites I tried your solution it works great locally  but for some reason my CI is throwing this error.

```
Jest encountered an unexpected token

This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
If you need a custom transformation specify a "transform" option in your config.
If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/en/configuration.html

Details:

/node_modules/react-native/jest/preprocessor.js:45
...nodeOptions,
^^^

SyntaxError: Unexpected token ...

at ScriptTransformer._getTransformer (node_modules/jest-runtime/build/script_transformer.js:231:19)
```

**Comment by thomashagstrom** [comment]
Now we're using TypeScript, if that matters. The above configuration, as suggested, does work. But also yields warning:

> ts-jest][DEPRECATED] - replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section of you
r Jest config with just "ts-jest".

However, just using ts-jest has the error come back.

```
 "transform": {
      "\\.(ts|tsx)$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
```

**Comment by Nigh7Sh4de** [comment]
@michaelknoch I had to install `babel-jest` as per https://jestjs.io/docs/en/getting-started#using-babel (although I didn't end up needing `babel-core`). Here is my final list of babel depencies:
```
"@babel/core": "^7.1.0",
"@babel/runtime": "^7.0.0",
"babel-jest": "^23.6.0",
```

**Comment by jonathonlui** [comment]
Looks like version 0.47 of `metro-react-native-babel-preset` is available now. Testing now works for me with this new version including `jest.mock`.

**Comment by hanford** [comment]
I finally resolved this issue by bringing in `https://www.npmjs.com/package/babel-plugin-jest-hoist` to my project.

My dependencies:

```json
    "react": "16.5.1",
    "react-native": "^0.57.1",
.. 
    "@babel/core": "^7.1.0",
    "@babel/runtime": "^7.0.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.1.1",
    "babel-jest": "^23.6.0",
    "babel-plugin-jest-hoist": "^23.2.0",
    "babel-plugin-relay": "^1.5.0",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "^0.47.0",
```

and my `babel.config.js`:
```js
module.exports = {
  "presets": ["module:metro-react-native-babel-preset", "module:react-native-dotenv"],
  "plugins": [
    "relay",
    "jest-hoist"
  ]
}
```

**Comment by michaelknoch** [comment]
still running into `Couldn't find preset "module:metro-react-native-babel-preset"` with 0.47.0

**Comment by luissmg** [comment]
Hey @michaelknoch. I have the following versions:

```
"react": "16.5.1",
"react-native": "^0.57.1",
...
"@babel/cli": "^7.0.0",
"@babel/core": "^7.0.0",
"jest": "^23.6.0",
"metro-react-native-babel-preset": "^0.45.0",
```

And it works just fine. Just had to change my `.babelrc` to `babel.config.js`, no need to install anything else.

**Comment by hernancorigliano** [comment]
I had the same issue and adding this to jest config made test work
`"^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",`
But then my `jest.mock()` statements were not working. It seems all the jest.mock() calls need to be hoisted before all `import` statements in the test.

**Comment by luissmg** [comment]
@hernancorigliano try what I said above

**Comment by hanford** [comment]
I've also been following this issue trying to track the jest.mock breakage

**Comment by michaelknoch** [comment]
I fixed most of my tests by moving mocks to `__MOCKS__` directory instead of mocking dynamically in the test itself. @hanford

**Comment by hernancorigliano** [comment]
> @hernancorigliano try what I said above

Sorry I forgot to mention that I tried using the plugin to hoist the calls, but for some reason does not seem to be working. I did exactly the same as you. I might have a problem with babel somewhere else.

**Comment by denieler** [comment]
looks like I've set
```
"jest": {
    "preset": "react-native",
```
and it works, even if I have installed only `metro-react-native-babel-preset`. Not sure why...

**Comment by xe4me** [comment]
inside my react-native-vector-icons folder, in node_modules, there was a bablerc file which was like this 

```
{
  "presets": ["module:metro-react-native-babel-preset"]
}

```

I manually changed it to this : 

```
{
  "presets": ["react-native"]
}

```

**Comment by msaifa** [comment]
I hope this can help
1. Go to new module folder (ex: node_module/react-native-vector-icons)
2. Open .babelrc
3. replace `"presets": ["module:metro-react-native-babel-preset"]`
4. with ` "presets": ["react-native"]`
5. and rebuild project

trims

**Comment by microsockss** [comment]
> And it works just fine. Just had to change my `.babelrc` to `babelrc.js` and install `babel-core` (`npm i -D babel-core@bridge`).
Can confirm this works for me!

**Comment by esbenp** [comment]
After I added the custom transform mocks stopped working as well.

I added

`'babel-core@^7.0.0-bridge'`

and removed the custom transform and changed from `.babelrc` to `babel.config.js`

```
module.exports = function (api) {
  api.cache(true)
  return {
    "presets": ["module:metro-react-native-babel-preset"]
  };
}
```

now my tests are running and mocks are working as usual :-) hope it can help somebody

**Comment by ospfranco** [comment]
After spending a couple of hours trying to make everything work, I noticed there is some official documentation for ts-jest to run on react-native 0.57 and babel 7:

https://kulshekhar.github.io/ts-jest/user/react-native/

Solved my problem

**Comment by makabde** [comment]
> After I added the custom transform mocks stopped working as well. These are the steps I completed to fix it.
> 
>     1. I added `'babel-core@^7.0.0-bridge'`
> 
>     2. **removed** the custom transform (`transform: { '^.+\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js' }`)
> 
>     3. changed from `.babelrc` to `babel.config.js`
> 
> 
> **babel.config.js**
> 
> ```
> module.exports = function (api) {
>   api.cache(true)
>   return {
>     "presets": ["module:metro-react-native-babel-preset"]
>   };
> }
> ```
> 
> now my tests are running and mocks are working as usual :-) hope it can help somebody

This solution worked for me but I also had to bring `@babel/plugin-proposal-class-properties` to my `devDependencies`
https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-class-properties

**Comment by hieunc229** [comment]
@makabde It worked for me too, without adding `@babel/plugin-proposal-class-properties`

**Comment by ferdicus** [comment]
one thing I noticed and was taken aback by was, that jest is caching tests.
So if you think "why aren't my babel config changes doing anything", chances are, that jest is running the tests out of it's cache without considering the config changes.

Make sure to run `jest --clearCache` when trying to test config changes.

**Comment by igorrfc** [comment]
@esbenp worked for me. Thanks, man !

**Comment by ramanandapanda** [comment]
I was facing the same issue and while implementing detox e2e test.
fixed it by adding the following code in the e2e/config.json
```"transform": {
        "^.+\\.js$": "<rootDir>/../node_modules/react-native/jest/preprocessor.js"
      }```
under the main {}.
my file config.json is
```
{
    "setupTestFrameworkScriptFile": "./init.js",
    "testEnvironment": "node",
    "transform": {
        "^.+\\.js$": "<rootDir>/../node_modules/react-native/jest/preprocessor.js"
      }
}
```

**Comment by henrique1977** [comment]
@esbenp's suggestion worked for me as well. 

@esbenp, you rock!! 

Thank you!

**Comment by btravel** [comment]
@esbenp solution works for me, except of missed transform: 
`transform: {
    '^.+\\.(js|jsx)$': '<rootDir>/node_modules/react-native/jest/preprocessor.js',
  },`

I've returned it to be able to use ES6 syntax in my test files.

**Comment by haswalt** [comment]
Can confirm @esbenp solution works, in fact the only one here that works. Thanks!

**Comment by itinance** [comment]
This issue occur also on a newly fresh installed version of an react-native application:

```
react-native init test
cd test
react-native-git-upgrade
```

gives

> git-upgrade ERR! An error occurred during upgrade:
> git-upgrade ERR! Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/private/tmp/xxx"
>     at /usr/local/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
>     at Array.map (<anonymous>)

**Comment by debugpai** [comment]
I was getting this error when running tests with [detox](https://github.com/wix/Detox)
@esbenp s solution worked for me to remove the error with not finding metro bundler. However I started getting the error 
`ReferenceError: regeneratorRuntime is not defined`. 

On removing the line `disableBabelRuntime: true` from `react-native/jest/preprocessor.js` this error goes away. This change was introduced by [this commit](https://github.com/facebook/react-native/commit/89a358f34786198c8a9a2d379588efd57b6a0eec)

To fix it temporarily, I copied `react-native/jest/preprocessor.js` to `<project_root>/jest-preprocessor.js` and removing `disableBabelRuntime: true` and directing the path to `transform` to this file.

**Comment by liangguohun** [comment]
so i choose to use the old version

**Comment by harveyconnor** [comment]
I didn't test with jest, but this lets me run `npm start`:
`npm i metro-react-native-babel-preset --save-dev`

**Comment by binhxn** [comment]
Just echoing other solutions above... depending on your use case, use only one:
`.babelrc` or `babel.config.js` (as per [documentation](https://babeljs.io/docs/en/configuration))

For me, I was in the process of migrating my code and had both files present by accident, so the bundler was confused. I removed `.babelrc` and kept `babel.config.js` and the error went away.

**Comment by dsaharia** [comment]
> Hey @michaelknoch. I have the following versions:
> 
> ```
> "react": "16.5.1",
> "react-native": "^0.57.1",
> ...
> "@babel/cli": "^7.0.0",
> "@babel/core": "^7.0.0",
> "babel-core": "^7.0.0-bridge.0",
> "jest": "^23.6.0",
> "metro-react-native-babel-preset": "^0.45.0",
> ```
> 
> And it works just fine. Just had to change my `.babelrc` to `babelrc.js` and install `babel-core` (`npm i -D babel-core@bridge`).

Thanks a ton, man

**Comment by SORNVENGE** [comment]
> I have found the same problem today.
> Open the file `.babelrc`, you will find it in the root of the project, and replace:
> 
> `{ "presets": ["module:metro-react-native-babel-preset"] } `
> 
> to
> 
> `{ "presets": ["react-native"] } `

It worked only react-native version <=0.61 but for version 0.63 it doesn't work.

**Comment by zhiqingchen** [comment]
This file is no longer available since 0.70

> I was facing the same issue and while implementing detox e2e test. fixed it by adding the following code in the e2e/config.json
> 
> ```
> "transform": {
> "^.+\\.js$": "<rootDir>/../node_modules/react-native/jest/preprocessor.js"
> }
> ```
> 
> under the main {}. my final config.json file looks like this:
> 
> ```
> {
>     "setupTestFrameworkScriptFile": "./init.js",
>     "testEnvironment": "node",
>     "transform": {
>         "^.+\\.js$": "<rootDir>/../node_modules/react-native/jest/preprocessor.js"
>       }
> }
> ```

**Comment by robhogan** [comment]
We're triaging older issues. `metro-react-native-babel-preset` has been replaced by `@react-native/babel-preset`, so this configuration no longer applies to supported React Native versions.
