### ISSUE TITLE
metro image can not require work?

### ISSUE THREAD

**Issue by LiuC520** [react/metro#371]
Node.js Version:
v10.15.3
OS:
 Mac
Scope (install, code, runtime, meta, other?):
runtime/other
Module (and version) (if relevant):
React-Native 

I create a new file named "metro.config.js", 
and  a file named "images", where i put a png photo .

metro.config.js:
```js
function getExtraNodeModules(extraModules) {
  const extraNodeModules = {}
  Object.keys(extraModules).forEach((moduleName) => {
    extraNodeModules[moduleName] = `${__dirname}/${extraModules[moduleName]}`
  })

  return extraNodeModules
}

const extraNodeModules = Object.assign(
  {},
  getExtraNodeModules({
    images:`${__dirname}/images`,
  }),
)

module.exports = {
  projectRoot: path.resolve(__dirname),
  resolver: {
    extraNodeModules
  },
  watchFolders: [
    path.resolve(__dirname, 'images'),
  ],
}
```

I use Image in my react native code like this:
```js
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
      <Image source={require('images/videosPlay.png')} size={{
          width: 120,
          height: 120
        }} />
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

when run npm start and reload pages, I got 
```
error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/images'
    at Object.readdirSync (fs.js:785:3)
    at Object.getDirFiles (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro/src/node-haste/DependencyGraph.js:103:34)
    at Map.AssetResolutionCache.dirPath [as _factory] (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro/src/node-haste/AssetResolutionCache.js:41:36)
    at Map.get (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro/src/node-haste/lib/MapWithDefaults.js:25:24)
    at AssetResolutionCache.resolve (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro/src/node-haste/AssetResolutionCache.js:91:43)
    at resolveAsset (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro/src/node-haste/DependencyGraph.js:227:36)
    at resolveAssetFiles (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro-resolver/src/resolve.js:456:22)
    at resolveFile (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro-resolver/src/resolve.js:342:20)
    at resolveFileOrDir (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro-resolver/src/resolve.js:255:22)
    at Object.resolve (/Users/vittorio/Desktop/rn/test/test0_58_6/node_modules/metro-resolver/src/resolve.js:148:20)
```

**Comment by yinhangfeng** [comment]
same error

project struct

```
.
└── src/
    ├── assets/
```

metro.config.js

```javascript
// ...
resolver: {
  extraNodeModules: {
    $: path.resolve(__dirname, 'src'),
  },
},
// ...
```

import png
```javascript
import testPng from '$/assets/test.png';
```

error

```
error: bundling failed: Error: ENOENT: no such file or directory, scandir '.../TestProject/src/node_modules/$/assets'
    at Object.readdirSync (fs.js:786:3)
    at Object.getDirFiles (/Users/yinhf/work/wind/windwork-feature/node_modules/metro/src/node-haste/DependencyGraph.js:103:34)
    at Map.AssetResolutionCache.dirPath [as _factory] (/Users/yinhf/work/wind/windwork-feature/node_modules/metro/src/node-haste/AssetResolutionCache.js:44:32)
    at Map.get (/Users/yinhf/work/wind/windwork-feature/node_modules/metro/src/node-haste/lib/MapWithDefaults.js:23:24)
    at AssetResolutionCache.resolve (/Users/yinhf/work/wind/windwork-feature/node_modules/metro/src/node-haste/AssetResolutionCache.js:102:43)
    at resolveAsset (/Users/yinhf/work/wind/windwork-feature/node_modules/metro/src/node-haste/DependencyGraph.js:229:36)
    at resolveAssetFiles (/Users/yinhf/work/wind/windwork-feature/node_modules/metro-resolver/src/resolve.js:473:22)
    at resolveFile (/Users/yinhf/work/wind/windwork-feature/node_modules/metro-resolver/src/resolve.js:359:20)
    at resolveFileOrDir (/Users/yinhf/work/wind/windwork-feature/node_modules/metro-resolver/src/resolve.js:272:22)
    at Object.resolve (/Users/yinhf/work/wind/windwork-feature/node_modules/metro-resolver/src/resolve.js:160:20)
```

**Comment by robhogan** [comment]
Metro used to throw early during asset resolution before consulting `extraNodeModules`. That was fixed in ce6824ced, Metro v0.52.0.
