### ISSUE TITLE
Cannot read property 'update' of undefined when trying to bundle

### ISSUE THREAD

**Issue by AyushG3112** [react/metro#416]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Error While trying to bundle APK

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Running
```
./gradlew --info assembleRelease
```
In turn runs
```
node  ./node_modules/react-native/cli.js bundle --platform android --dev false --reset-cache --entry-file index.js --bundle-output /home/ayush/myProject/android/app/build/generated/assets/react/release/index.android.bundle --assets-dest /home/ayush/myProject/android/app/build/generated/res/react/release --verbose
```
which throws error:
```
error Cannot read property 'update' of undefined
debug TypeError: Cannot read property 'update' of undefined
    at new Server (/home/ayush/myProject/node_modules/metro/src/Server.js:675:29)
    at buildBundle (/home/ayush/myProject/node_modules/@react-native-community/cli/build/commands/bundle/buildBundle.js:91:18)
```
**What is the expected behavior?**
Bundle should be built successfully

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
Ubuntu 16.04/18.04
node 10.15.0
yarn version v1.16.0

    "metro-react-native-babel-preset": "^0.54.0",
    "react": "16.8.3",
    "react-native": "0.59.5",

**Comment by KristineTrona** [comment]
@AyushG3112 I had the same issue. Check if you have the latest react-native-cli version installed, remove the lockfile and node_modules and reinstall the packages. Solved the problem for me.

You can also check out: 
https://github.com/react-native-community/cli/issues/374

**Comment by AyushG3112** [comment]
@KristineTrona I tried that but that didn't work for me.

What worked for me was to add the following block to `metro.config.js`:

```
reporter: {
    update: () => {}
}
```
