### ISSUE TITLE
Hello. Error starting the project, react native 0.60.4

### ISSUE THREAD

**Issue by shanematte** [react/metro#440]
`error: bundling failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument mu
st be of type string. Received type boolean`

`    at assertPath (path.js:39:11)
    at Object.dirname (path.js:651:5)
    at resolveFileOrDir (S:\apps\react_native\app\node_modules\metro-resol
ver\src\resolve.js:260:24)
    at Object.resolve (S:\apps\react_native\app\node_modules\metro-resolve
r\src\resolve.js:155:20)
    at ModuleResolver.resolveDependency (S:\apps\react_native\app\node_mod
ules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:143:31)
    at ResolutionRequest.resolveDependency (S:\apps\react_native\app\node_
modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (S:\apps\react_native\app\node_mo
dules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (S:\apps\react_native\app\node_modules\metro\src\lib
\transformHelpers.js:264:42)
    at dependencies.map.result (S:\apps\react_native\app\node_modules\metr
o\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
 BUNDLE  [android, dev] ./index.js 24.1% (220/545), failed
`

**Comment by robhogan** [comment]
We're triaging older issues. This was caused by the resolver passing a `false` browser-field redirection into `path.dirname()` while checking `node_modules` candidates. It was fixed in [`0f1846a`](https://github.com/facebook/metro/commit/0f1846a64d7ec27ad7c42b1aee2a049e0fad9a5a) and released in Metro 0.76.0.
