### ISSUE TITLE
[metro-config] `transformer.workerPath` should be an absolute path not a relative path

### ISSUE THREAD

**Issue by vjpr** [react/metro#617]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Bundling fails when using expo + pnpm monorepo with multiple versions of `metro`.

This is the stack trace from the worker process:

```
TypeError: Transformer.transform is not a function
    at Object.<anonymous> (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:80:38)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:14:24)
    at _next (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:36:9)
    at /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:43:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:32:12)
    at Object._transform (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:98:21)
    at Object.transform (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.64.0/node_modules/metro/src/DeltaBundler/Worker.js:55:21)
    at execFunction (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/workers/processChild.js:155:17) {
  type: 'TypeError'
```

And this is the stack trace from the call that instantiates the worker pool:

```
Error
    at WorkerFarm.transform (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.58.0/node_modules/metro/src/DeltaBundler/WorkerFarm.js:120:17)
    at /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.58.0/node_modules/metro/src/DeltaBundler/Transformer.js:222:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.58.0/node_modules/metro/src/DeltaBundler/Transformer.js:46:24)
    at _next (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/metro@0.58.0/node_modules/metro/src/DeltaBundler/Transformer.js:66:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

Notice how `metro@0.58.0` is used in the main process, and the child processes use a different version.

Metro should pass the absolute path of the worker instead of a relative path.

It will never be safe for a `jest-worker` to use a relative path: https://github.com/facebook/jest/issues/10934

## Fix

This worker path should be changed to `require.resolve`.

https://github.com/facebook/metro/blob/d6eefe44bdc163c04b3ada92d825451b52ecf41a/packages/metro-config/src/defaults/index.js#L116

## Workaround (for pnpm)

_rn-cli.config.js_

```js
// See https://facebook.github.io/metro/docs/en/configuration.
module.exports = {
  transformer: {
	// Set this to an absolute path to your `metro/src/DeltaBundler/Worker` for the version you want.
    workerPath: getWorkerPath(),
  },
}

function getWorkerPath() {
  // The default is set in https://github.com/facebook/metro/blob/d6eefe44bdc163c04b3ada92d825451b52ecf41a/packages/metro-config/src/defaults/index.js#L116
  // As of 202012, it is 'metro/src/DeltaBundler/Worker'.
  const workerPath =
    '/node_modules/.pnpm/metro@0.58.0/node_modules/metro/src/DeltaBundler/Worker.js'
  const repoRoot = getRepoRoot()
  return require.resolve(path.join(repoRoot, workerPath))
}

function getRepoRoot() {
  return path.dirname(findUp.sync('pnpm-workspace.yaml', {cwd: process.cwd()}))
}

```

**Comment by XxQuickSilverZz** [comment]
`workerPath: process.env.DEV === true ? require.resolve('/web/node_modules/metro/src/DeltaBundler/Worker.js'): 'metro/src/DeltaBundler/Worker'`

**Comment by robhogan** [comment]
We’re triaging older issues. This was fixed in Metro 0.77.0. Metro now resolves the worker to an absolute path before passing it to `jest-worker`, preventing a different hoisted Metro version from being selected.
