### ISSUE TITLE
metro-hermes-compiler: abort runtime error

### ISSUE THREAD

**Issue by birkir** [react/metro#678]
```
/Users/birkir/Projects/xxx/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^

RuntimeError: abort(TypeError: Cannot read property 'url' of undefined). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/birkir/Projects/xxx/node_modules/metro-hermes-compiler/src/emhermesc.js:796:13)
    at process.emit (events.js:376:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

No idea what this means, or how to debug it.

Works fine when entry point only includes one `console.log`, but once I import something from `react-native` it will throw this.

I updated node version from v14.16.0 to v14.17.0

**Comment by Marvedog** [comment]
experiencing this too with node version `12.22.1`

**Comment by andreecueva97** [comment]
Lo solucione borrando node_modules\metro-hermes-compiler. Luego use el siguiente comando: npm i metro-hermes-compiler 

Luego me funciono todo bien.

**Comment by birkir** [comment]
Found out that having a resolution for "ws" in package.json will cause this, do not do that.

**Comment by robhogan** [comment]
Closing as obsolete. `metro-hermes-compiler` was removed in Metro 0.77.0, together with Metro's experimental support for compiling JavaScript to Hermes bytecode. The Hermes compiler is now distributed with React Native.
