### ISSUE TITLE
Bug report: React Native Error when remote JS Debug is enabled

### ISSUE THREAD

**Issue by akinwale-habibullah** [react/metro#694]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
when I enabled (Debug with Chrome when using react-native) or (Debug remote JS when using expo) in the device simulator, it results in an error:

`Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:614:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/akinwalehabib/Documents/ReactNativeProject/node_modules/metro/src/Server.js:1471:14`

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
- Create a new project using either create-react-native or react-native
- Run react-native start
- In another tab, run npm run ios
- In the device simulator, press COMMAND + D
- Select Debug with Chrome (react-native) or Debug Remote JS (Expo)
- Check the logs in React Native

**What is the expected behavior?**
I expect to see what I logged out from my application, with no errors generated.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
- OS: MacOS Catalina (Version 10.15.7)
- react-native: 0.64.2
-

**Comment by peaceful-james** [comment]
I am having the same problem on Linux with react-native 0.64.2

I read this discussion: https://github.com/itinance/react-native-fs/issues/991
and did the following

1. I installed `patch-package` (`yarn install patch-package`)

2. I edited `node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js` and changed this line

```
if (error.code === "ENOENT")
```

to this:

```
if (error.code === "ENOENT" || error.code === "EISDIR")
```

3. I ran `npx patch-package metro`. This created a "patch" file in a directory called `patches`.

4. I committed the patch to my git repository.

My problem is **not** solved but now when I run my React Native app I get a different error message:

```
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from MY_PROJECT_PATH.:

None of these files exist:
  * debugger-ui/debuggerWorker.acaxxxxx(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json)
```

I am following this conversation too: https://github.com/facebook/metro/issues/658 This problem is very confusing for me!

**Comment by Jason-NIU** [comment]
Anyone has a resolution yet?  it seems that it happens after RN 0.62

**Comment by fatemehmarzoughi** [comment]
Same here

**Comment by manish0707** [comment]
Getting the same issue

**Comment by lfoliveir4** [comment]
Same issue

**Comment by robhogan** [comment]
Closing as obsolete. This affected the legacy Remote JavaScript Debugging flow served from Metro's `/debugger-ui`. React Native deprecated that flow and removed it from the Dev Menu in 0.73. React Native DevTools has been the default debugging experience since 0.76.
