### ISSUE TITLE
compose-source-maps failure after manual changes  upgrade 0.70.5 => 0.71.3 (Task :app:createBundleReleaseJsAndAssets or manual scripts)

### ISSUE THREAD

**Issue by alexkrav** [react/metro#938]
### New Version

0.71.3

### Old Version

0.70.5

### Build Target(s)

android

### Output of `react-native info`

System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.14 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.05.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/alexkrav/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 33.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

After manual changes using Upgrade Helper android build task `:app:createBundlePreReleaseJsAndAssets` failed on creation of compose map

 ```
> Task :app:createBundlePreReleaseJsAndAssets
warn Package @react-native-community/google-signin contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warning: the transform cache was reset.
                Welcome to Metro v0.73.7
              Fast - Scalable - Integrated


Waiting for Watchman `query` (10s)...
Watchman `query` finished after 11.6s.
transform[stderr]: Error: infinite loop while processing mergePaths plugin.
transform[stderr]: Error: infinite loop while processing mergePaths plugin.
info Writing bundle output to:, /Users/alexkrav/TEST/neutron-0.71.x/android/app/build/ASSETS/createBundlePreReleaseJsAndAssets/index.android.bundle
info Writing sourcemap output to:, /Users/alexkrav/TEST/neutron-0.71.x/android/app/build/intermediates/sourcemaps/react/preRelease/index.android.bundle.packager.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 1136 asset files
info Done copying assets
...
Error: Invalid mapping: {"generated":{"line":1,"column":1023478},"source":"/Users/alexkrav/TEST/neutron-0.71.x/node_modules/react-native-device-info/src/index.ts","original":{"line":38,"column":-1},"name":null}
    at SourceMapGenerator.SourceMapGenerator_validateMapping [as _validateMapping] (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator.SourceMapGenerator_addMapping [as addMapping] (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/composeSourceMaps.js:42:15
    at MappingsConsumer.eachMapping (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/Consumer/AbstractConsumer.js:34:16)
    at composeSourceMaps (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/composeSourceMaps.js:36:16)
    at Object.<anonymous> (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/react-native/scripts/compose-source-maps.js:59:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
```

**I could easily to reach the same error just performing create compose map (does not need to build):**

```
--------- 1. Bundle/minify with metro (react-native) to get the packager source map (.packager.map)
+ npx react-native bundle --platform android --dev true --minify false --entry-file index.js --bundle-output 
--------- 2. Compile to bytecode using hermes to get the compiler source map (.hbc.map)
+ ./node_modules/react-native/sdks/hermesc/osx-bin/hermesc -w -O -emit-binary -output-source-map -out=./android/index.android.bundle.hbc ./android/index.android.bundle
--------- 3. Merge the two source maps using compose-source-maps to get the final source map (.map)
+ node node_modules/react-native/scripts/compose-source-maps.js ./android/index.android.bundle.packager.map ./android/index.android.bundle.hbc.map -o ./android/index.android.bundle.map

/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:289
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":1648084},"source":"/Users/alexkrav/TEST/neutron-0.71.x/node_modules/react-native-device-info/src/index.ts","original":{"line":38,"column":-1},"name":null}
    at SourceMapGenerator.SourceMapGenerator_validateMapping [as _validateMapping] (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator.SourceMapGenerator_addMapping [as addMapping] (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/composeSourceMaps.js:42:15
    at MappingsConsumer.eachMapping (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/Consumer/AbstractConsumer.js:34:16)
    at composeSourceMaps (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/metro-source-map/src/composeSourceMaps.js:36:16)
    at Object.<anonymous> (/Users/alexkrav/TEST/neutron-0.71.x/node_modules/react-native/scripts/compose-source-maps.js:59:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
```

**Comment by cortinico** [comment]
Passing over to metro as the error happened during the bundling phase

**Comment by robhogan** [comment]
Hi @alexkrav - this sounds like it could be https://github.com/facebook/metro/pull/928, related to our switch to Terser as a default minifier. Could you check whether the problem goes away by switching to `metro-minify-uglify`?

```js
// metro.config.js

module.exports = {
  transformer: {
    minifierPath: require.resolve('metro-minify-uglify')
    // ...
  }
  // ...
}
```

If so, this fix will be part of RN 0.71.4, and you can safely use `'metro-minify-uglify'` in the mean time.

**Comment by alexkrav** [comment]
Hi @robhogan ,
Thank you for suggestion.
I've added line proposed into `metro.config.js../transformer` but unfortunately, it did not  fix the problem - the same error reported.

**Comment by alexkrav** [comment]
@robhogan  ,
I've tried to use newest `metro-source-map` v.0.75.1 with your fix for #928 in the following script:
```
--------- 1. Bundle/minify with metro (react-native) to get the packager source map (.packager.map)
+ npx react-native bundle --platform android --dev true --minify false --entry-file index.js --bundle-output 
--------- 2. Compile to bytecode using hermes to get the compiler source map (.hbc.map)
+ ./node_modules/react-native/sdks/hermesc/osx-bin/hermesc -w -O -emit-binary -output-source-map -out=./android/index.android.bundle.hbc ./android/index.android.bundle
--------- 3. Merge the two source maps using compose-source-maps to get the final source map (.map)
+ node node_modules/react-native/scripts/compose-source-maps.js ./android/index.android.bundle.packager.map ./android/index.android.bundle.hbc.map -o ./android/index.android.bundle.map
```
still fails with the same mapping error.
Note that bundle created with `--minify false` param.

**Comment by robhogan** [comment]
Thanks for trying that - definitely seems like a different issue and one we're unaware of. 

Would you be able to put up a minimal GitHub repo or steps I can use to reproduce from a new project? I'll have a bit of time tomorrow to try to investigate if so.

**Comment by alexkrav** [comment]
@robhogan 
This is very big  project and I do not know how to extract reproducible part. 

What I've found - that if bundle is created with `--minify true` then above script finishes successfully.

**Comment by robhogan** [comment]
I'd like to get to the bottom of this but I'm stuck without a reproduction. On a new project this works:

```sh
$ npx react-native@latest init RNMetroIssue938 && cd RNMetroIssue938
$ node node_modules/react-native/scripts/compose-source-maps.js ./android/index.android.bundle.packager.map ./android/index.android.bundle.hbc.map -o ./android/index.android.bundle.map
$ ./node_modules/react-native/sdks/hermesc/osx-bin/hermesc -w -O -emit-binary -output-source-map -out=./android/index.android.bundle.hbc ./android/index.android.bundle
$ npx react-native bundle --platform android --dev false --minify false --entry-file index.js --bundle-output ./android/index.android.bundle --sourcemap-output ./android/index.android.bundle.packager.map
```

So, the issue seems to be triggered by something in your project code or the dependencies it imports.

If you have time, I'd suggest taking a clone of your project (which I'm guessing you can't share?) and stub / comment / delete big chunks of it until the problem goes away, then work back from there to narrow it down to maybe a bit of code or particular dependency, and then try to reproduce it with just that bit in a new app.

**Comment by Hless** [comment]
Chiming in on this issue, not sure if related. 

I'm on RN 0.66.5 still, recently upgraded from 0.66.4, and this exact issue started happening n my project as well. Bundling with `--minify true` also fixes it for me. I'm at a complete loss how this suddenly started happening.

I'm guessing it's a transient dependency that got updated in the meantime that is causing this. We have a massive amount of deps in a monorepo, so it would be extremely difficult to track the culprit down.

@alexkrav Do you have any progress on this issue so far?

**Comment by alexkrav** [comment]
@Hless 
No progress with this. Using `--minify true`
On 0.71: to avoid build crash I had to uncomment/modify two options in app/build.gradle:
```
...
    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    debuggableVariants = ["regularDebug"]
...
    /* Bundling */
    extraPackagerArgs = [ '--minify=true', '--dev=false' ]
```

**Comment by robhogan** [comment]
Closing for lack of a reproduction. This was never narrowed down beyond a large private app, and there's been nothing further since 2023.

For anyone arriving here, the only clue was that `--minify false` triggered it while `--minify true` didn't, and the failing mappings had out-of-range original positions (`column: -1`, `line: 0`). If you can reproduce it on a current Metro, please open a new issue with a project we can run.
